const express=require('express')
const router=express.Router()
const registerFun=require('../controllers/user.controller')
const upload=require("../middlwares/multer")
router.post('/userRegister',upload.single('Image'), registerFun.register)
router.post('/otp',registerFun.otpVerification)
router.post('/login',registerFun.login)
router.post('/logout',registerFun.logout)
router.get('/me',registerFun.me)
module.exports=router